let savedX = null;
let savedY = null;

function makeDraggable(element) {
    let isDragging = false;
    let offsetX, offsetY;

    element.onmousedown = function (event) {
        isDragging = true;
        offsetX = event.clientX - element.getBoundingClientRect().left;
        offsetY = event.clientY - element.getBoundingClientRect().top;

        document.onmousemove = function (event) {
            if (isDragging) {
                const newX = event.clientX - offsetX;
                const newY = event.clientY - offsetY;

                // Update the position of the element
                element.style.left = newX + 'px';
                element.style.top = newY + 'px';

                // Save the position in global variables
                savedX = newX;
                savedY = newY;
            }
        };

        document.onmouseup = function () {
            isDragging = false;
            document.onmousemove = null;
            document.onmouseup = null;
        };
    };
}

function universesMenu() {
    let ttnwMenu = document.getElementById('universesMenu');
    let controls = document.getElementById('controls');
    if (!ttnwMenu) {
        ttnwMenu = document.createElement('div');
        ttnwMenu.id = 'universesMenu';
        document.body.insertBefore(ttnwMenu, controls);

        const menuTitle = document.createElement('h1');
        menuTitle.innerText = 'THE UNIVERSE-EXPLAINER 7000';
        menuTitle.id = 'menuTitle'
        ttnwMenu.appendChild(menuTitle);

        const universeViewer = document.createElement('img');
        universeViewer.id = 'universeViewer';
        ttnwMenu.appendChild(universeViewer);

        const universeController = document.createElement('div');
        universeController.id = 'universeController';

        const backKey = document.createElement('a');
        backKey.classList = 'universeToggle'
        backKey.onclick = function() { prevUniverse(); };
        backKey.innerHTML = '&lt;';

        const universeName = document.createElement('p');
        universeName.id = 'universeName';

        const forwardKey = document.createElement('a');
        forwardKey.classList = 'universeToggle'
        forwardKey.onclick = function() { nextUniverse(); };
        forwardKey.innerHTML = '&gt;';

        universeController.appendChild(backKey);
        universeController.appendChild(universeName);
        universeController.appendChild(forwardKey);

        const universeDescription = document.createElement("p");
        universeDescription.id = "universeDescription";
        ttnwMenu.appendChild(universeController);
        ttnwMenu.appendChild(universeDescription);

        makeDraggable(ttnwMenu);
    }

    if (savedX !== null && savedY !== null) {
        ttnwMenu.style.left = savedX + 'px';
        ttnwMenu.style.top = savedY + 'px';
    }
    else {
        ttnwMenu.style.left = 1+'px';
        ttnwMenu.style.top = 0;
        savedX = ttnwMenu.getBoundingClientRect().left;
        savedY = ttnwMenu.getBoundingClientRect().top;
    }
}

universesMenu()

let universes = [
    {
        photo: "",
        universe: "IRL (Real Life™)",
        descriptor: "Known to HWC as 'the world beyond ours', this is where you, the viewer, reside. We leverage ultimate power over the CCC as the people who make rips and write lore."
    },
    {
        photo: "",
        universe: "CCC",
        descriptor: "Otherwise known as the Central Canon Continuum, this is the main universe around which all other parallel universes and timelines circle around."
    },
    {
        photo: "",
        universe: "Reboot Universe",
        descriptor: "A temporary universe generated by The Voice Inside Your Head during the Reboot, where the channel's three biggest memes were replaced in a bid to stop Chad Warden."
    },
    {
        photo: "",
        universe: "BLACK Timeline",
        descriptor: "An alternate timeline where Chad Warden was more like his real self and went on an omnicidal rampage across Earth. The Voice had premonitions of this timeline and started the Reboot to prevent it."
    },
    {
        photo: "",
        universe: "AIRTH",
        descriptor: "The domain of the now-dead SiIva AI, this was the universe that SiIvaGunner focused on from 2018 to 2022, including both the King for a Day and King for Another Day tournaments."
    },
    {
        photo: "",
        universe: "MS Paint",
        descriptor: "One of the two universes in the Mashup Crusaders arc, defined by its backgrounds being made in MS Paint. Originally the home of Mr. Own before 2B showed up."
    },
    {
        photo: "",
        universe: "Looney Tunes",
        descriptor: "The other of two universes in the Mashup Crusaders arc, being entirely monochrome. Originally the home of Mr. Rental before 2B showed up."
    },
    {
        photo: "",
        universe: "CCC-FOOLS",
        descriptor: "Christened by Dr. Andonuts in [FILE-18]. Reader and Jerome live here, in what they consider to be the 'real world'. Has its own version of the CCC."
    },
    {
        photo: "",
        universe: "Omegaverse",
        descriptor: "Known by a variety of alternative names due to the unfortunate implications of the term 'Omega'. Gegagedi, Boykisser, Pomni and Charlie, The Steak call this universe home."
    },
    {
        photo: "",
        universe: "Sanrioverse",
        descriptor: "A universe primarily based on the Hello Kitty franchise. The Kitty Inside Your Head and Hello Kitty live here."
    },
    {
        photo: "",
        universe: "GORKiverse",
        descriptor: "All of SiIvaGunner's live action skits take place in this universe, which has recently been canonised in lore due to the GORK ARG."
    },
    {
        photo: "",
        universe: "Kirby Fighters",
        descriptor: "A world inspired by early 2000s Youtube/Newgrounds animations. Originally the home of Waluigi before he was sent to the CCC."
    },
    {
        photo: "",
        universe: "The Void",
        descriptor: "First seen in <b>The Disappearance of Wood Man</b>, this is where both he and Susie reside. Events of the ∇e arc also imply that dead Figments may go here after dying."
    },
];

let universeIndex = 0;
let title = document.getElementById("universeName");
universeParser() //initialise universe viewer

function prevUniverse() {
    universeIndex += -1
    if (universeIndex < 0) {
        universeIndex = universes.length - 1;
    }
    universeParser(universeIndex);
};

function nextUniverse() {
    universeIndex += 1;

    if (universeIndex >= universes.length) {
        universeIndex = 0;
    }

    universeParser(universeIndex);
}

function universeParser() {
    let currentUniverse = universes[universeIndex]
    let title = document.getElementById("universeName");
    let description = document.getElementById("universeDescription");
    title.innerHTML = currentUniverse.universe;
    description.innerHTML = currentUniverse.descriptor;
};





